"""Add pluggy credit and merchant fields

Revision ID: 43edad7d83e8
Revises: 812215574290
Create Date: 2026-03-19 19:13:43.494396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43edad7d83e8'
down_revision: Union[str, Sequence[str], None] = '812215574290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balance_close_date', sa.Date(), nullable=True))
    op.add_column('accounts', sa.Column('balance_due_date', sa.Date(), nullable=True))
    op.add_column('accounts', sa.Column('credit_level', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('merchant_cnpj', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('merchant_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'merchant_name')
    op.drop_column('transactions', 'merchant_cnpj')
    op.drop_column('accounts', 'credit_level')
    op.drop_column('accounts', 'balance_due_date')
    op.drop_column('accounts', 'balance_close_date')
    # ### end Alembic commands ###
