"""Add custom_account_fields

Revision ID: f55e22d48a15
Revises: 094a893578cd
Create Date: 2026-03-18 22:43:48.228077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55e22d48a15'
down_revision: Union[str, Sequence[str], None] = '094a893578cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('custom_name', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('accounts', sa.Column('account_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_number')
    op.drop_column('accounts', 'sort_order')
    op.drop_column('accounts', 'custom_name')
    # ### end Alembic commands ###
